### ISSUE TITLE
Link to Synchrotron out-of-date

### ISSUE THREAD

**Issue by tonyg** [langram/node-diff3#6]
Hi! If you wouldn't mind, please update the link from the old homepages.kcbbs.gen.nz site to <https://leastfixedpoint.com/tonyg/kcbbs/projects/synchrotron.html>. Thanks!

**Comment by bhousel** [comment]
Hey @tonyg, I don't think langram/node-diff3 is maintained anymore, but I am keeping it alive over at bhousel/node-diff3 and I have updated the links there 👍
